CREATE TABLE TYPECHAM
(
	CodTypChan	VARCHAR(2) 	NOT NULL PRIMARY KEY,
	DescTyp 	VARCHAR(25),
	NbDispo 	int(3)
);

CREATE TABLE LOCALISATION
(
	CodLoc 		VARCHAR(2)	NOT NULL PRIMARY KEY,
	DescLoc 	VARCHAR(25)
);

CREATE TABLE CHAMBRE
(
	NoCham 		VARCHAR(3) 	NOT NULL PRIMARY KEY,
	Etage 		VARCHAR(2),
	Prix 		DECIMAL(5,2),
	Etat 		TINYINT,
	Memo 		VARCHAR(MAX),
	CodLoc 		VARCHAR(2) 	FOREIGN KEY REFERENCES LOCALISATION(CodLoc),
	CodTypChan 	VARCHAR(2) 	FOREIGN KEY REFERENCES TYPECHAM(CodTypChan)
);

CREATE TABLE COMMODITE
(
	CodCom	VARCHAR(2)		NOT NULL PRIMARY KEY,
	DescCom VARCHAR(25)
);

CREATE TABLE AYANT
(
	NoCham 	VARCHAR(3) 	FOREIGN KEY REFERENCES CHAMBRE(NoCham),
	CodCom 	VARCHAR(2)	FOREIGN KEY REFERENCES COMMODITE(CodCom)
);
