USE h18equipe1;

DROP TABLE IF EXISTS h18equipe1.TYPECHAM;
DROP TABLE IF EXISTS h18equipe1.LOCALISATION;
DROP TABLE IF EXISTS h18equipe1.COMMODITE;
DROP TABLE IF EXISTS h18equipe1.CLIENT;
DROP TABLE IF EXISTS h18equipe1.TYPETRX;
DROP TABLE IF EXISTS h18equipe1.CHAMBRE;
DROP TABLE IF EXISTS h18equipe1.AYANT;
DROP TABLE IF EXISTS h18equipe1.RESERVATION;
DROP TABLE IF EXISTS h18equipe1.DE;
DROP TABLE IF EXISTS h18equipe1.DEPART;
DROP TABLE IF EXISTS h18equipe1.ARRIVE;
DROP TABLE IF EXISTS h18equipe1.TRX;

CREATE TABLE TYPECHAM
(
	CodTypChan	VARCHAR(2) 	NOT NULL PRIMARY KEY,
	DescTyp 	VARCHAR(25),
	NbDispo 	int
);

CREATE TABLE LOCALISATION
(
	CodLoc 		VARCHAR(2)	NOT NULL PRIMARY KEY,
	DescLoc 	VARCHAR(25)
);

CREATE TABLE COMMODITE
(
	CodCom		VARCHAR(2)	NOT NULL PRIMARY KEY,
	DescCom		VARCHAR(25)
);

CREATE TABLE CLIENT
(
	IdCli 		int				NOT NULL	IDENTITY(1,1),
	Nom 		VARCHAR(25)		NULL,
	Adresse 	VARCHAR(25)		NULL,
	Telephone 	VARCHAR(10)		NULL,
	NoCarte 	VARCHAR(16)		NULL,	
	TypeCarte 	VARCHAR(15)		NULL,
	DatExp 		DATE			NULL,
	SoldeDu 	DECIMAL(12,2)	NULL,
	PRIMARY KEY	(IdCli)
);

CREATE TABLE TYPETRX
(
	CodTypTrx 	VARCHAR(2) 		NOT NULL, 
	DescTrx 	VARCHAR(25)		NULL,
	Nature 		VARCHAR(2)		NULL,	
	PRIMARY KEY (CodTypTrx)
);

CREATE TABLE CHAMBRE
(
	NoCham 		VARCHAR(3) 	NOT NULL PRIMARY KEY,
	Etage 		VARCHAR(2),
	Prix 		DECIMAL(5,2),
	Etat 		TINYINT,
	Memo 		VARCHAR(MAX),
	CodLoc 		VARCHAR(2) 	FOREIGN KEY REFERENCES LOCALISATION(CodLoc),
	CodTypChan 	VARCHAR(2) 	FOREIGN KEY REFERENCES TYPECHAM(CodTypChan)
);

CREATE TABLE AYANT
(
	NoCham 	VARCHAR(3) 	FOREIGN KEY REFERENCES CHAMBRE(NoCham),
	CodCom 	VARCHAR(2)	FOREIGN KEY REFERENCES COMMODITE(CodCom)
);


CREATE TABLE RESERVATION
(
	IdReser     INT         NOT NULL    IDENTITY(1,1),
    IdCli       INT         NULL,
    DateReser   DATE        NULL,
    DateDebut   DATE        NULL,
    DateFin     DATE        NULL,
    PRIMARY KEY (IdReser),
    FOREIGN KEY (IdCli)     REFERENCES CLIENT(IdCli)
);

CREATE TABLE DE
(
    Attribuee	BIT			NULL,
    IdReser     INT         NULL,
    NoCham      VARCHAR(3)  NULL,
    FOREIGN KEY (IdReser)   REFERENCES RESERVATION(IdReser),
    FOREIGN KEY (NoCham)    REFERENCES CHAMBRE(NoCham)
);

CREATE TABLE DEPART
(
    IdDepart     INT        NOT NULL    IDENTITY(1,1),
    DateDepart   DATE       NULL,
    ConfirmerPar VARCHAR(6) NULL,
    IdReser      INT        NULL,
    NoCham       VARCHAR(6) NULL,
    IdCli        INT        NULL,
    PRIMARY KEY (IdDepart),
    FOREIGN KEY (IdReser)   REFERENCES RESERVATION(IdReser),
    FOREIGN KEY (NoCham)    REFERENCES CHAMBRE(NoCham),
    FOREIGN KEY (IdCli)     REFERENCES CLIENT(IdCli)
);


CREATE TABLE ARRIVE
(
	IdArrive 	int				NOT NULL	IDENTITY(1,1),
	DateArrive 	DATE 			NULL,
	IdCli 		int				NULL,
	IdReser 	int				NULL,
	NoCham 		VARCHAR(3)		NULL,
	PRIMARY KEY	(IdArrive),
	FOREIGN KEY (IdCli) 		REFERENCES CLIENT(IdCli),
	FOREIGN KEY (NoCham) 		REFERENCES CHAMBRE(NoCham),
	FOREIGN KEY (IdReser) 		REFERENCES RESERVATION(IdReser)
);


CREATE TABLE TRX (
	IdTrx 		int 			NOT NULL	IDENTITY(1,1),  
	DateTrx 	DATE			NULL,
	MontantTrx 	DECIMAL(10,2)	NULL,
	Reportee 	BIT				NULL,
	CodTypTrx 	VARCHAR(2)		NULL, 
	IdReser 	int				NULL, 
	NoCham 		VARCHAR(4) 		NULL,
	IdCli 		int 			NULL,
	IdArrive	int				NULL,
	PRIMARY KEY (IdTrx),
	FOREIGN KEY (CodTypTrx) 	REFERENCES TYPETRX(CodTypTrx),
	FOREIGN KEY (IdReser) 		REFERENCES RESERVATION(IdReser),
	FOREIGN KEY (NoCham)		REFERENCES CHAMBRE(NoCham),
	FOREIGN KEY (IdCli)			REFERENCES CLIENT(IdCli),
	FOREIGN KEY (IdArrive) 		REFERENCES ARRIVE(IdArrive)
);

