CREATE TABLE TYPETRX
(
	CodTypTrx 	VARCHAR(2) 		NOT NULL, 
	DescTrx 	VARCHAR(25)		NULL,
	Nature 		VARCHAR(2)		NULL,	
	PRIMARY KEY (CodTypTrx)
);

CREATE TABLE TRX (
	IdTrx 		int 			NOT NULL	IDENTITY(1,1),  
	DateTrx 	DATE			NULL,
	MontantTrx 	DECIMAL(10,2)	NULL,
	Reportee 	BIT				NULL,
	CodTypTrx 	VARCHAR(2)		NULL, 
	IdReser 	int				NULL, 
	NoCham 		VARCHAR(4) 		NULL,
	IdCli 		int 			NULL,
	PRIMARY KEY (IdTrx),
	FOREIGN KEY (CodTypTrx) REFERENCES TYPETRX(CodTypTrx),
	FOREIGN KEY (IdReser) 	REFERENCES RESERVATION(IdReser),
	FOREIGN KEY (NoCham)	REFERENCES CHAMBRE(NoCham),
	FOREIGN KEY (IdCli)		REFERENCES CLIENT(IdCli)
);
