USE H18EQ01;
CREATE TABLE CLIENT
(
	IdCli 		int				NOT NULL	IDENTITY(1,1),
	Nom 		VARCHAR(25)		NULL,
	Adresse 	VARCHAR(25)		NULL,
	Telephone 	VARCHAR(10)		NULL,
	NoCarte 	VARCHAR(16)		NULL,	
	TypeCarte 	VARCHAR(15)		NULL,
	DatExp 		DATE			NULL,
	SoldeDu 	DECIMAL(12,2)	NULL,
	PRIMARY KEY	(IdCli)
);

CREATE TABLE ARRIVE
(
	IdArrive 	int				NOT NULL	IDENTITY(1,1),
	DateArrive 	DATE 			NULL,
	IdCli 		int				NULL,
	IdReser 	int				NULL,
	NoCham 		VARCHAR(3)		NULL,
	PRIMARY KEY	(IdArrive),
	FOREIGN KEY (IdCli) 	REFERENCES CLIENT(IdCli),
	FOREIGN KEY (NoCham) 	REFERENCES CHAMBRE(NoCham),
	FOREIGN KEY (IdReser) 	REFERENCES RESERVATION(IdReser)
);

