USE h18equipe1;

DROP TABLE IF EXISTS TRX;
DROP TABLE IF EXISTS ARRIVE;
DROP TABLE IF EXISTS DEPART;
DROP TABLE IF EXISTS DE;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS AYANT;
DROP TABLE IF EXISTS CHAMBRE;
DROP TABLE IF EXISTS TYPETRX;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS COMMODITE;
DROP TABLE IF EXISTS LOCALISATION;
DROP TABLE IF EXISTS TYPECHAM;

CREATE TABLE TYPECHAM
(
	CodTypCham	VARCHAR(2) 		NOT NULL,
	DescTyp 	VARCHAR(25)		NULL,
	NbDispo 	int			NULL/*,
	PRIMARY KEY (CodTypCham)*/
);
ALTER TABLE TYPECHAM
	ADD CONSTRAINT TYPECHAM_PK_CodTypCham PRIMARY KEY CLUSTERED (CodTypCham)


CREATE TABLE LOCALISATION
(
	CodLoc 		VARCHAR(2)		NOT NULL,
	DescLoc 	VARCHAR(25)		NULL/*,
	PRIMARY KEY (CodLoc)*/
);
ALTER TABLE LOCALISATION
	ADD CONSTRAINT LOCALISATION_PK_CodLoc PRIMARY KEY CLUSTERED (CodLoc)


CREATE TABLE COMMODITE
(
	CodCom		VARCHAR(2)		NOT NULL,
	DescCom 	VARCHAR(25)		NULL/*,
	PRIMARY KEY (CodCom)*/
);
ALTER TABLE COMMODITE
	ADD CONSTRAINT COMMODITE_PK_CodCom PRIMARY KEY CLUSTERED (CodCom)


CREATE TABLE CLIENT
(
	IdCli 		int			NOT NULL	IDENTITY(1,1),
	Nom 		VARCHAR(25)		NULL,
	Adresse 	VARCHAR(25)		NULL,
	Telephone 	VARCHAR(10)		NULL,
	NoCarte 	VARCHAR(16)		NULL,	
	TypeCarte 	VARCHAR(15)		NULL,
	DatExp 		DATE			NULL,
	SoldeDu 	DECIMAL(12,2)		NULL/*,
	PRIMARY KEY	(IdCli)*/
);
ALTER TABLE CLIENT
	ADD CONSTRAINT CLIENT_PK_IdCli PRIMARY KEY CLUSTERED (IdCli)


CREATE TABLE TYPETRX
(
	CodTypTrx 	VARCHAR(2) 		NOT NULL, 
	DescTrx 	VARCHAR(25)		NULL,
	Nature 		VARCHAR(2)		NULL/*,	
	PRIMARY KEY (CodTypTrx)*/
);
ALTER TABLE TYPETRX
	ADD CONSTRAINT TYPETRX_PK_CodTypTrx PRIMARY KEY CLUSTERED (CodTypTrx)


CREATE TABLE CHAMBRE
(
	NoCham 		VARCHAR(3) 		NOT NULL,
	Etage 		VARCHAR(2)		NULL,
	Prix 		DECIMAL(5,2)		NULL,
	Etat 		TINYINT			NULL,
	Memo 		VARCHAR(MAX)		NULL,
	CodLoc 		VARCHAR(2)		NULL, 	
	CodTypCham 	VARCHAR(2)		NULL/*,
	PRIMARY KEY (NoCham),
	FOREIGN KEY (CodLoc)		REFERENCES LOCALISATION(CodLoc), 	
	FOREIGN KEY (CodTypCham)	REFERENCES TYPECHAM(CodTypCham)*/
);
ALTER TABLE CHAMBRE
	ADD CONSTRAINT CHAMBRE_PK_NoCham PRIMARY KEY CLUSTERED (NoCham)
ALTER TABLE CHAMBRE
	ADD CONSTRAINT CHAMBRE_FK_CodLoc FOREIGN KEY (CodLoc) REFERENCES LOCALISATION(CodLoc)
ALTER TABLE CHAMBRE
	ADD CONSTRAINT CHAMBRE_FK_CodTypCham FOREIGN KEY (CodTypCham) REFERENCES TYPECHAM(CodTypCham)


CREATE TABLE AYANT
(
	NoCham 		VARCHAR(3) 		NULL,
	CodCom 		VARCHAR(2)		NULL/*,
	FOREIGN KEY (NoCham)	REFERENCES CHAMBRE(NoCham),	
	FOREIGN KEY (CodCom)	REFERENCES COMMODITE(CodCom)*/
);
ALTER TABLE AYANT
	ADD CONSTRAINT AYANT_FK_NoCham FOREIGN KEY (NoCham) REFERENCES CHAMBRE(NoCham)
ALTER TABLE AYANT
	ADD CONSTRAINT AYANT_FK_CodCom FOREIGN KEY (CodCom) REFERENCES COMMODITE(CodCom)


CREATE TABLE RESERVATION
(
	IdReser     	INT         		NOT NULL    IDENTITY(1,1),
    	IdCli       	INT         		NULL,
    	DateReser   	DATE        		NULL,
    	DateDebut   	DATE        		NULL,
    	DateFin     	DATE        		NULL/*,
    	PRIMARY KEY (IdReser),
    	FOREIGN KEY (IdCli)     REFERENCES CLIENT(IdCli)*/
);
ALTER TABLE RESERVATION
	ADD CONSTRAINT RESERVATION_PK_IdReser PRIMARY KEY CLUSTERED (IdReser)
ALTER TABLE RESERVATION
	ADD CONSTRAINT RESERVATION_FK_IdCli FOREIGN KEY (IdCli) REFERENCES CLIENT(IdCli)


CREATE TABLE DE
(
    	Attribuee		BIT					NULL,
    	IdReser     	INT         		NULL,
    	NoCham      	VARCHAR(3)  		NULL/*,
    	FOREIGN KEY (IdReser)   REFERENCES RESERVATION(IdReser),
    	FOREIGN KEY (NoCham)    REFERENCES CHAMBRE(NoCham)*/
);
ALTER TABLE DE
	ADD CONSTRAINT DE_FK_IdReser FOREIGN KEY (IdReser) REFERENCES RESERVATION(IdReser)
ALTER TABLE DE
	ADD CONSTRAINT DE_FK_NoCham FOREIGN KEY (NoCham) REFERENCES CHAMBRE(NoCham)


CREATE TABLE DEPART
(
    	IdDepart     	INT        		NOT NULL    IDENTITY(1,1),
    	DateDepart   	DATE       		NULL,
    	ConfirmerPar 	VARCHAR(6) 		NULL,
    	IdReser      	INT        		NULL,
    	NoCham       	VARCHAR(3) 		NULL,
    	IdCli        	INT        		NULL/*,
    	PRIMARY KEY (IdDepart),
    	FOREIGN KEY (IdReser)   REFERENCES RESERVATION(IdReser),
    	FOREIGN KEY (NoCham)    REFERENCES CHAMBRE(NoCham),
    	FOREIGN KEY (IdCli)     REFERENCES CLIENT(IdCli)*/
);
ALTER TABLE DEPART
	ADD CONSTRAINT DEPART_PK_IdDepart PRIMARY KEY CLUSTERED (IdDepart)
ALTER TABLE DEPART
	ADD CONSTRAINT DEPART_FK_IdReser FOREIGN KEY (IdReser) REFERENCES RESERVATION(IdReser)
ALTER TABLE DEPART
	ADD CONSTRAINT DEPART_FK_NoCham FOREIGN KEY (NoCham) REFERENCES CHAMBRE(NoCham)
ALTER TABLE DEPART
	ADD CONSTRAINT DEPART_FK_IdCli FOREIGN KEY (IdCli) REFERENCES CLIENT(IdCli)


CREATE TABLE ARRIVE
(
	IdArrive 	int			NOT NULL	IDENTITY(1,1),
	DateArrive 	DATE 			NULL,
	IdCli 		int			NULL,
	IdReser 	int			NULL,
	NoCham 		VARCHAR(3)		NULL/*,
	PRIMARY KEY	(IdArrive),
	FOREIGN KEY (IdCli) 		REFERENCES CLIENT(IdCli),
	FOREIGN KEY (NoCham) 		REFERENCES CHAMBRE(NoCham),
	FOREIGN KEY (IdReser) 		REFERENCES RESERVATION(IdReser)*/
);
ALTER TABLE ARRIVE
	ADD CONSTRAINT ARRIVE_PK_IdArrive PRIMARY KEY CLUSTERED (IdArrive)
ALTER TABLE ARRIVE
	ADD CONSTRAINT ARRIVE_FK_IdCli FOREIGN KEY (IdCli) REFERENCES CLIENT(IdCli)
ALTER TABLE ARRIVE
	ADD CONSTRAINT ARRIVE_FK_NoCham FOREIGN KEY (NoCham) REFERENCES CHAMBRE(NoCham)
ALTER TABLE ARRIVE
	ADD CONSTRAINT ARRIVE_FK_IdReser FOREIGN KEY (IdReser) REFERENCES RESERVATION(IdReser)


CREATE TABLE TRX 
(
	IdTrx 		int 			NOT NULL	IDENTITY(1,1),  
	DateTrx 	DATE			NULL,
	MontantTrx 	DECIMAL(10,2)		NULL,
	Reportee 	BIT			NULL,
	CodTypTrx 	VARCHAR(2)		NULL, 
	IdReser 	int			NULL, 
	NoCham 		VARCHAR(3) 		NULL,
	IdCli 		int 			NULL,
	IdArrive	int			NULL/*,
	PRIMARY KEY (IdTrx),
	FOREIGN KEY (CodTypTrx) 	REFERENCES TYPETRX(CodTypTrx),
	FOREIGN KEY (IdReser) 		REFERENCES RESERVATION(IdReser),
	FOREIGN KEY (NoCham)		REFERENCES CHAMBRE(NoCham),
	FOREIGN KEY (IdCli)		REFERENCES CLIENT(IdCli),
	FOREIGN KEY (IdArrive) 		REFERENCES ARRIVE(IdArrive)*/
);
ALTER TABLE TRX
	ADD CONSTRAINT TRX_PK_IdTrx PRIMARY KEY CLUSTERED (IdTrx)
ALTER TABLE TRX
	ADD CONSTRAINT TRX_FK_CodTypTrx FOREIGN KEY (CodTypTrx) REFERENCES TYPETRX(CodTypTrx)
ALTER TABLE TRX
	ADD CONSTRAINT TRX_FK_IdReser FOREIGN KEY (IdReser) REFERENCES RESERVATION(IdReser)
ALTER TABLE TRX
	ADD CONSTRAINT TRX_FK_NoCham FOREIGN KEY (NoCham) REFERENCES CHAMBRE(NoCham)
ALTER TABLE TRX
	ADD CONSTRAINT TRX_FK_IdCli FOREIGN KEY (IdCli) REFERENCES CLIENT(IdCli)
ALTER TABLE TRX
	ADD CONSTRAINT TRX_FK_IdArrive FOREIGN KEY (IdArrive) REFERENCES ARRIVE(IdArrive)
